name: Continous Integration build for Fhi.Frontend.ReactComponent
on: [pull_request]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          registry-url: 'https://registry.npmjs.org/'
      - name: Build 
        run: |
         npm install
         
      - name: Debug installed packages
        run: npm list @types/styled-components

      - name: Debug all @types packages
        run: ls -l node_modules/@types

      - name: Debug TypeScript module resolution
        run: npx tsc --traceResolution
        
      - name: Run prepack
        run: npm run prepack
